runtime: go112

handlers:
  - url: /client/(.*\.(gif|png|jpeg|jpg|css|js|ico))$
    static_files: client/\1
    upload: client/(.*)
  - url: /client/(.*)
    static_files: client/index.html
    upload: client/index.html
  - url: /.*
    script: auto